
volumes:
  postgres_volume_local:

services:
  pg-local:
    image: postgres:16-alpine3.21
    env_file:
      - "local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  migrator-local:
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local