name: CI for Chat Server

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

env:
  REGISTRY: "cr.selcloud.ru/nick-resh"
  IMAGE_NAME: "chat-server"
  CONTAINER_NAME: "chat-server-container"

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login $REGISTRY -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push \
            --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME \
            -f ./Dockerfile .
          
  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-push

    steps:
    - name: Deploy to Selectel via SSH
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSHKEY }}
        envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME
        script: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)

          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

          docker run -d -p 50052:50052 --name $CONTAINER_NAME -t $REGISTRY/$IMAGE_NAME:$TAG_NAME

